### ISSUE TITLE
InvalidArgumentError: indices[498] = 65282 is not in [0, 65280)

### ISSUE THREAD

**Issue by 3carras3** [arangesh/HandyNet#2]
I tried to run demo_inference.py as instructed in the readme. I used the already trained model offered (handynet.h5) and a random .mat smooth depth file extracted from the HandyNet dataset. 

```
python3 scripts/demo_inference.py /home/adrian/Downloads/handynet.h5 /home/adrian/Downloads/samplemat2.mat
```
However, I get the following output: 
```
OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0-7
OMP: Info #213: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #276: KMP_AFFINITY: Affinity capable, using global cpuid leaf 11 info
OMP: Info #156: KMP_AFFINITY: 8 available OS procs
OMP: Info #157: KMP_AFFINITY: Uniform topology
OMP: Info #191: KMP_AFFINITY: 1 socket x 4 cores/socket x 2 threads/core (4 total cores)
OMP: Info #215: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #171: KMP_AFFINITY: OS proc 0 maps to socket 0 core 0 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 4 maps to socket 0 core 0 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 1 maps to socket 0 core 1 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 5 maps to socket 0 core 1 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 2 maps to socket 0 core 2 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 6 maps to socket 0 core 2 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 3 maps to socket 0 core 3 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 7 maps to socket 0 core 3 thread 1 
OMP: Info #251: KMP_AFFINITY: pid 17526 tid 17526 thread 0 bound to OS proc set 0
Using TensorFlow backend.

Configurations:
BACKBONE_SHAPES                [[128 128]
 [ 64  64]
 [ 32  32]
 [ 16  16]
 [  8   8]]
BACKBONE_STRIDES               [4, 8, 16, 32, 64]
BATCH_SIZE                     1
BBOX_STD_DEV                   [0.1 0.1 0.2 0.2]
DETECTION_MAX_INSTANCES        10
DETECTION_MIN_CONFIDENCE       0.5
DETECTION_NMS_THRESHOLD        0.3
GPU_COUNT                      1
IMAGES_PER_GPU                 1
IMAGE_MAX_DIM                  512
IMAGE_MIN_DIM                  423
IMAGE_PADDING                  True
IMAGE_SHAPE                    [512 512   3]
LEARNING_MOMENTUM              0.9
LEARNING_RATE                  0.001
MASK_POOL_SIZE                 14
MASK_SHAPE                     [28, 28]
MAX_GT_INSTANCES               10
MEAN_PIXEL                     [0. 0. 0.]
MINI_MASK_SHAPE                (56, 56)
NAME                           HandyNet
NUM_CLASSES                    6
POOL_SIZE                      7
POST_NMS_ROIS_INFERENCE        100
POST_NMS_ROIS_TRAINING         100
ROI_EXPANSION_FACTOR           0.5
ROI_POSITIVE_RATIO             0.33
RPN_ANCHOR_RATIOS              [0.5, 1, 2]
RPN_ANCHOR_SCALES              (16, 32, 64, 128)
RPN_ANCHOR_STRIDE              1
RPN_BBOX_STD_DEV               [0.1 0.1 0.2 0.2]
RPN_NMS_THRESHOLD              0.7
RPN_TRAIN_ANCHORS_PER_IMAGE    64
STEPS_PER_EPOCH                1000
TRAIN_ROIS_PER_IMAGE           20
USE_MINI_MASK                  False
USE_RPN_ROIS                   True
USE_SMART_TRAIN_ROIS           False
VALIDATION_STEPS               1257
WEIGHT_DECAY                   0.0001


WARNING:tensorflow:From /home/adrian/anaconda2/envs/handynet/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:508: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/adrian/anaconda2/envs/handynet/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:68: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From /home/adrian/anaconda2/envs/handynet/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:3837: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

WARNING:tensorflow:From /home/adrian/anaconda2/envs/handynet/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:3661: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

WARNING:tensorflow:From /home/adrian/anaconda2/envs/handynet/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:1944: The name tf.image.resize_nearest_neighbor is deprecated. Please use tf.compat.v1.image.resize_nearest_neighbor instead.

WARNING:tensorflow:From /home/adrian/workspace/programs/HandyNet/scripts/model.py:321: The name tf.log is deprecated. Please use tf.math.log instead.

WARNING:tensorflow:From /home/adrian/workspace/programs/HandyNet/scripts/model.py:375: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From /home/adrian/workspace/programs/HandyNet/scripts/model.py:399: calling crop_and_resize_v1 (from tensorflow.python.ops.image_ops_impl) with box_ind is deprecated and will be removed in a future version.
Instructions for updating:
box_ind is deprecated, use box_indices instead
WARNING:tensorflow:From /home/adrian/workspace/programs/HandyNet/scripts/model.py:812: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.
    
WARNING:tensorflow:From /home/adrian/anaconda2/envs/handynet/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:168: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

2020-03-25 18:33:09.114227: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2020-03-25 18:33:09.137179: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2099940000 Hz
2020-03-25 18:33:09.137465: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x563991229150 executing computations on platform Host. Devices:
2020-03-25 18:33:09.137500: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2020-03-25 18:33:09.137683: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
2020-03-25 18:33:10.330897: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
OMP: Info #251: KMP_AFFINITY: pid 17526 tid 17547 thread 1 bound to OS proc set 1
OMP: Info #251: KMP_AFFINITY: pid 17526 tid 17548 thread 2 bound to OS proc set 2
OMP: Info #251: KMP_AFFINITY: pid 17526 tid 17549 thread 3 bound to OS proc set 3
OMP: Info #251: KMP_AFFINITY: pid 17526 tid 17551 thread 5 bound to OS proc set 5
OMP: Info #251: KMP_AFFINITY: pid 17526 tid 17550 thread 4 bound to OS proc set 4
OMP: Info #251: KMP_AFFINITY: pid 17526 tid 17552 thread 6 bound to OS proc set 6
OMP: Info #251: KMP_AFFINITY: pid 17526 tid 17553 thread 7 bound to OS proc set 7
OMP: Info #251: KMP_AFFINITY: pid 17526 tid 17554 thread 8 bound to OS proc set 0
OMP: Info #251: KMP_AFFINITY: pid 17526 tid 17546 thread 9 bound to OS proc set 1
OMP: Info #251: KMP_AFFINITY: pid 17526 tid 17555 thread 10 bound to OS proc set 2
OMP: Info #251: KMP_AFFINITY: pid 17526 tid 17556 thread 11 bound to OS proc set 3
OMP: Info #251: KMP_AFFINITY: pid 17526 tid 17557 thread 12 bound to OS proc set 4
OMP: Info #251: KMP_AFFINITY: pid 17526 tid 17558 thread 13 bound to OS proc set 5
OMP: Info #251: KMP_AFFINITY: pid 17526 tid 17559 thread 14 bound to OS proc set 6
OMP: Info #251: KMP_AFFINITY: pid 17526 tid 17560 thread 15 bound to OS proc set 7
OMP: Info #251: KMP_AFFINITY: pid 17526 tid 17561 thread 16 bound to OS proc set 0
Traceback (most recent call last):
  File "/home/adrian/anaconda2/envs/handynet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/adrian/anaconda2/envs/handynet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/adrian/anaconda2/envs/handynet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[498] = 65282 is not in [0, 65280)
         [[{{node ROI/GatherV2_2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/demo_inference.py", line 41, in <module>
    results = model.detect([image], verbose=0)
  File "/home/adrian/workspace/programs/HandyNet/scripts/model.py", line 2437, in detect
    self.keras_model.predict([molded_images, image_metas], verbose=0)
  File "/home/adrian/anaconda2/envs/handynet/lib/python3.6/site-packages/keras/engine/training.py", line 1835, in predict
    verbose=verbose, steps=steps)
  File "/home/adrian/anaconda2/envs/handynet/lib/python3.6/site-packages/keras/engine/training.py", line 1331, in _predict_loop
    batch_outs = f(ins_batch)
  File "/home/adrian/anaconda2/envs/handynet/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2482, in __call__
    **self.session_kwargs)
  File "/home/adrian/anaconda2/envs/handynet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/adrian/anaconda2/envs/handynet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/adrian/anaconda2/envs/handynet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/adrian/anaconda2/envs/handynet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[498] = 65282 is not in [0, 65280)
         [[node ROI/GatherV2_2 (defined at /home/adrian/workspace/programs/HandyNet/scripts/model.py:271) ]]

Errors may have originated from an input operation.
Input Source operations connected to node ROI/GatherV2_2:
 ROI/strided_slice_5 (defined at /home/adrian/workspace/programs/HandyNet/scripts/utils.py:681)

Original stack trace for 'ROI/GatherV2_2':
  File "scripts/demo_inference.py", line 28, in <module>
    model = modellib.MaskRCNN(mode="inference", model_dir='', config=config)
  File "/home/adrian/workspace/programs/HandyNet/scripts/model.py", line 1820, in __init__
    self.keras_model = self.build(mode=mode, config=config)
  File "/home/adrian/workspace/programs/HandyNet/scripts/model.py", line 1936, in build
    config=config)([rpn_class, rpn_bbox])
  File "/home/adrian/anaconda2/envs/handynet/lib/python3.6/site-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/adrian/workspace/programs/HandyNet/scripts/model.py", line 273, in call
    names=["pre_nms_anchors"])
  File "/home/adrian/workspace/programs/HandyNet/scripts/utils.py", line 682, in batch_slice
    output_slice = graph_fn(*inputs_slice)
  File "/home/adrian/workspace/programs/HandyNet/scripts/model.py", line 271, in <lambda>
    anchors = utils.batch_slice(ix, lambda x: tf.gather(anchors, x),
  File "/home/adrian/anaconda2/envs/handynet/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/adrian/anaconda2/envs/handynet/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 3475, in gather
    return gen_array_ops.gather_v2(params, indices, axis, name=name)
  File "/home/adrian/anaconda2/envs/handynet/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 4097, in gather_v2
    batch_dims=batch_dims, name=name)
  File "/home/adrian/anaconda2/envs/handynet/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/adrian/anaconda2/envs/handynet/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/adrian/anaconda2/envs/handynet/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/home/adrian/anaconda2/envs/handynet/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
```
I get a equivalent error when running the training with:
`python3 handynet.py train --dataset=/path/to/dataset/ --model=imagenet`

I'm using a conda enviroment with tf 1.14.0 and keras 2.1.16
Ubuntu 18.04.4
Also, running on machine with no GPU. Therefore, GPU_COUNT=1 in InferenceConfig for CPU inference as instructed. 

Additionally,  in case it helps pointing to the source of the problem:
Found a similar errors in [https://github.com/matterport/Mask_RCNN/issues/1291](url) and [https://github.com/matterport/Mask_RCNN/issues/946](url) that seem related. One solution that is claimed to work is to work in Mask_RCNN is to comment out the line RPN_ANCHOR_SCALES = (32, 64)
Reference:[https://github.com/matterport/Mask_RCNN/issues/946#issuecomment-425621062](url)

So, for the sake of trying, I did the same in handynet.py, commenting the line :
` RPN_ANCHOR_SCALES = (16, 32, 64, 128) # originally (32, 64, 128, 256, 512)`
Surprisingly, the error disappeared. And now both training and inference run without errors.
However, this can't be alright. And of course it isn't. Inference is completed but yields incorrect predictions (I will attach example image if requested) or fails altogether stating `*** No instances to display *** `.

Any clues about why this error happens? Or how it may be connected to RPN_ANCHOR_SCALES? Could it be due to using CPU instead of GPU?

Any help would be greatly apreciated.

**Comment by arangesh** [comment]
Thanks for the detailed error trace. For now, I can confirm that this seems to be an issue arising from using the CPU instead of the GPU for training and inference. 

I created two identical environments in Anaconda, except that one uses tensorflow-gpu and the other uses plain tensorflow (version 1.13.1 for both). The code runs perfectly well in the tensorflow-gpu environment, but produces the same error as yours in the tensorflow environment. My best guess is that certain tensorflow functions behave differently depending on whether they are CPU or GPU variants.

**Comment by arangesh** [comment]
Can you try changing the following line in the `handynet.py` file and try running the inference again?
```
RPN_ANCHOR_SCALES = (16, 32, 64, 128, 256) # originally (32, 64, 128, 256, 512)
```
I basically added an additional scale to match the number of feature pyramid levels. This produced the desired result at my end.

**Comment by 3carras3** [comment]
Thanks for the fast reply!
I made your proposed change and it works at my end too. Many thanks.
How come that mismatch on the number of levels doesn't produce errors with tensorflow-gpu?

**Comment by arangesh** [comment]
This might be because of different behavior of CPU and GPU variants of ``tf.gather()``. While the CPU variant throws an error when the index exceeds the size of the dimension, it does not for the GPU version and hence execution proceeds as normal. See [this link](https://github.com/tensorflow/tensorflow/issues/5847) for more details.

**Comment by 3carras3** [comment]
I will check it, thank you for the detailed response.
